stages:
  - build

build:
  stage: build
  image: openjdk:11
  script:
    - './build.sh'

test:
  stage: build
  image: openjdk:11
  script:
    - "apt update && apt install git-lfs"
    - "git lfs install"
    - "git clone https://gitlab.com/robocup-small-size/autoref-tests.git modules/moduli-autoreferee/autoref-tests"
    - "(cd modules/moduli-autoreferee/autoref-tests && git lfs fetch)"
    - './gradlew --stacktrace --no-daemon check integrationTest'
  artifacts:
    name: "${CI_JOB_NAME}_$CI_COMMIT_REF_NAME"
    when: on_failure
    expire_in: 1 week
    paths:
      - "data/record/"
      - "modules/*/build/reports/tests/*"
    reports:
      junit:
        - "modules/*/build/test-results/*/TEST-*.xml"
