image: cimg/openjdk:17.0

build:
  script:
    - './build.sh'

test:
  script:
    - "set -e"
    - "git clone https://gitlab.com/robocup-small-size/autoref-tests.git modules/moduli-autoreferee/config/autoref-tests"
    - "git -C modules/moduli-autoreferee/config/autoref-tests lfs pull"
    - './gradlew --stacktrace check integrationTest'
  artifacts:
    name: "${CI_JOB_NAME}_$CI_COMMIT_REF_NAME"
    when: on_failure
    expire_in: 1 week
    paths:
      - "data/record/"
      - "modules/*/build/reports/tests/*"
    reports:
      junit:
        - "modules/*/build/test-results/*/TEST-*.xml"
