name: Build and push to docker

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Publish to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: ./gradlew jib
      - name: Install curl
        run: sudo apt-get install -y curl
      - name: Trigger Docker Hub build
        env:
          BUILD_TRIGGERS: ${{ secrets.BUILD_TRIGGERS }}
        run: ./.github/workflows/trigger_docker.sh
