name: Perform Release

on:
  push:
    tags:
      - version/*

jobs:
  release:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: temurin
      - name: Publish auto-referee to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          tag=${GITHUB_REF#refs/tags/version/*}
          ./gradlew jib -Pversion=$tag
      - name: Publish auto-referee-vnc to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          tag=${GITHUB_REF#refs/tags/version/*}
          docker build --pull --build-arg base_version=$tag -t "tigersmannheim/auto-referee-vnc:$tag" src/main/docker-vnc
          docker login -u "${DOCKER_HUB_USERNAME}" -p "${DOCKER_HUB_PASSWORD}"
          docker push "tigersmannheim/auto-referee-vnc:$tag"
      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=${GITHUB_REF#refs/tags/version/*}
          ./gradlew githubRelease -Pversion=$tag
